### ISSUE TITLE
Followup to this: https://serverfault.com/questions/911247/routing-traffic-through-openvpn-on-kubernetes-with-calico

### ISSUE THREAD

**Issue by hugbubby** [ball-hayden/uk_account_validator#11]
https://xkcd.com/979/

Sorry but I can't seem to find any other way to contact you. How did you end up solving/working around this problem? I'm not using IBM, but DOKS, and wireguard instead of openvpn.

**Comment by ball-hayden** [comment]
I didn't. We moved off IBM, dropped our VPN setup, and completely rearchitected.
