### ISSUE TITLE
Generating valid UK Account numbers

### ISSUE THREAD

**Issue by aitor** [ball-hayden/uk_account_validator#14]
I know it is a long shot, but I was looking for ways to generate valid UK accounts for testing purposes, and I was wondering if there was any way to use the weight tables used by this gem to accomplish it.. any suggestions?

**Comment by ball-hayden** [comment]
An interesting question @aitor.

Firstly, a reminder that this gem attempts to validate that an account number/sort code combination _could_ be valid, not that it _is_ valid. There's no guarantee that the specific account actually exists.

You can find all the details for how modulus checking works at https://www.vocalink.com/tools/modulus-checking/.
I don't _think_ that the process is reversible I'm afraid.

Depending how many you need, my suggestion would be to pick a couple of sort codes and brute force some account numbers that validate?
From there, you've a list of possible combinations you can select from at random?
